// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asa_server_controller.Data;

#nullable disable

namespace asa_server_controller.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430143217_AddExposedGamePort")]
    partial class AddExposedGamePort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("asa_server_controller.Data.Entities.ClusterSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClusterSettings", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.CurseForgeSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurseForgeSettings", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.EmailSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.InvitationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteLink")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OneTimeVpnKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OneTimeVpnKey")
                        .IsUnique();

                    b.HasIndex("RemoteServerId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.LoginMethodTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LoginMethodTypes", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.ModEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurseForgeModId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurseForgeModId")
                        .IsUnique();

                    b.ToTable("Mods", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.NfsShareInviteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteLink")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteKey")
                        .IsUnique();

                    b.HasIndex("RemoteServerId");

                    b.ToTable("NfsShareInvites", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.RemoteServerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("ApiKeyHash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExposedGamePort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GamePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ServerInfoCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VpnAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("IpAddress");

                    b.HasKey("Id");

                    b.ToTable("RemoteServers", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.RemoteServerModEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModEntityId");

                    b.HasIndex("RemoteServerId", "ModEntityId")
                        .IsUnique();

                    b.ToTable("RemoteServerMods", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwoFactorSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.UserLoginMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoginMethodTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoginMethodTypeId");

                    b.HasIndex("UserId", "LoginMethodTypeId")
                        .IsUnique();

                    b.ToTable("UserLoginMethods", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.VpnServerSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedIps")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistentKeepalive")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresharedKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VpnServerSettings", (string)null);
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.InvitationEntity", b =>
                {
                    b.HasOne("asa_server_controller.Data.Entities.RemoteServerEntity", "RemoteServer")
                        .WithMany("Invitations")
                        .HasForeignKey("RemoteServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteServer");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.NfsShareInviteEntity", b =>
                {
                    b.HasOne("asa_server_controller.Data.Entities.RemoteServerEntity", "RemoteServer")
                        .WithMany("NfsShareInvites")
                        .HasForeignKey("RemoteServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteServer");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.RemoteServerModEntity", b =>
                {
                    b.HasOne("asa_server_controller.Data.Entities.ModEntity", null)
                        .WithMany()
                        .HasForeignKey("ModEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asa_server_controller.Data.Entities.RemoteServerEntity", null)
                        .WithMany()
                        .HasForeignKey("RemoteServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.User", b =>
                {
                    b.HasOne("asa_server_controller.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.UserLoginMethodEntity", b =>
                {
                    b.HasOne("asa_server_controller.Data.Entities.LoginMethodTypeEntity", "LoginMethodType")
                        .WithMany("UserLoginMethods")
                        .HasForeignKey("LoginMethodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asa_server_controller.Data.Entities.User", "User")
                        .WithMany("LoginMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoginMethodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.LoginMethodTypeEntity", b =>
                {
                    b.Navigation("UserLoginMethods");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.RemoteServerEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("NfsShareInvites");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("asa_server_controller.Data.Entities.User", b =>
                {
                    b.Navigation("LoginMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
